### ISSUE TITLE
put `self.event_generate(` to `VKeyboard.py`

### ISSUE THREAD

**Issue by WK-GiHu** [Justinjay282/qwerty#22]
@WK-GiHu, I'm thinking of it until now... I'm sorry if I'm very slow on this...  I did some revisions. I put `self.event_generate('<<IDLE>>', state = 0, when = 'tail')` to `VKeyboard.py` and added `class SplashThread(threading.Thread)` in `Kiosk_main.py`

_Originally posted by @Justinjay282 in https://github.com/Justinjay282/qwerty/issues/19#issuecomment-590074805_

**Comment by WK-GiHu** [comment]
@Justinjay282 

>I only need to put the `self.master.event_generate('<<IDLE>>', state = 0, when = 'tail')`  to `VKeyboard.py`

### Why didn't you **copy and past**, compare the above statement with this:
https://github.com/Justinjay282/qwerty/blob/9a13b4739bd9176baa5208d403dda3cc10b43866/VKeyboard.py#L22

As it stands, it's useless. 
Read the point **1.** from https://github.com/Justinjay282/qwerty/issues/19#issuecomment-590055279 again, **where** to put this statement.

---

**Comment by Justinjay282** [comment]
@WK-GiHu, sir, In `FingerprintThread` the `self.event_generate('<<IDLE>>', state = 0, when = 'tail')` is on `def run` I'm thinking do I need to create another `class varname(threading.Thread)` inside `VKeyboard.py`?

**Comment by WK-GiHu** [comment]
@Justinjay282 

>I'm thinking do I need to create another class varname(threading.Thread) inside VKeyboard.py?

### STOP
You don't need to `create` anything new.
### Read the point 1. from #19 (comment) again, where to put this statement.

**Comment by Justinjay282** [comment]
sir @WK-GiHu, that statement will be put in `VKeyboard.py`...

**Comment by Justinjay282** [comment]
> @Justinjay282
> 
> > I'm thinking do I need to create another class varname(threading.Thread) inside VKeyboard.py?
> 
> ### STOP
> You don't need to `create` anything new.
> 
> ### Read the point 1. from #19 (comment) again, where to put this statement.

**Comment by WK-GiHu** [comment]
@Justinjay282 

### No progress here!

- [ ] Still not fulfilled https://github.com/Justinjay282/qwerty/issues/22#issuecomment-590077500

**Comment by Justinjay282** [comment]
@WK-GiHu, sir, sorry I didn't notice that I typed `self.` instead of `self.master`

**Comment by WK-GiHu** [comment]
@Justinjay282 

### No progress here!

- [ ] Still not fulfilled https://github.com/Justinjay282/qwerty/issues/22#issuecomment-590077500

**Comment by WK-GiHu** [comment]
@Justinjay282 

### On point more...

- [ ] Still not fulfilled, read again https://github.com/Justinjay282/qwerty/issues/22#issuecomment-590077500

**Comment by Justinjay282** [comment]
> ### On point more...
> * [ ]  Still not fulfilled, read again [#22 (comment)](https://github.com/Justinjay282/qwerty/issues/22#issuecomment-590077500)

sir, @WK-GiHu, I just want to ask what do I need to do here?

**Comment by WK-GiHu** [comment]
@Justinjay282 

>what do I need to do here?

The place where you put
https://github.com/Justinjay282/qwerty/blob/07f5335f64a685b2dce347a3777453038beb71b3/VKeyboard.py#L35 
ist not the requested one.

Follow the chained ***read again*** links and try to understand the linked sentence **1.**.

**Comment by Justinjay282** [comment]
@WK-GiHu, sir, I'm reading over and over again... **inside `VKeyboard` send the following event at every touch/click** 
`self.master.event_generate('<<IDLE>>', state=0, when='tail')`

is it to be put on `def on_idle`? or it will be put in the `toplevel()` GUI to be made...

**Comment by WK-GiHu** [comment]
@Justinjay282 

>I just thought it will be put in VKeyboard __init__ but it;s wrong...

Yes, it's wrong, because it's **not the point** where any `touch/click` get processed.

Ask yourself, **where**, inside of `class VKeyboard`, are the `touch/click` callbacks get processed?
You have to finde this point to **reset** the idel counter, using `.event_generate(...`, at **every `touch/click`**.

**Comment by Justinjay282** [comment]
> Ask yourself, **where**, inside of `class VKeyboard`, are the `touch/click` callbacks get processed?
> You have to finde this point to **reset** the idel counter, using `.event_generate(...`, at **every `touch/click`**.

sir, @WK-GiHu, so it will be put in `def on_idle`? since the `touch/click` callbacks get processed there. It's also the reset of our counter right?

**Comment by WK-GiHu** [comment]
@Justinjay282 

>o it will be put in def on_idle? since the touch/click callbacks get processed there. It's also the reset of our counter right?

Wher do you see a `def on_idel(...` insde of `class VKeyboard`?
Read again https://github.com/Justinjay282/qwerty/issues/22#issuecomment-590311328

**Comment by Justinjay282** [comment]
@WK-GiHu, sir, I'm sorry I misunderstood, the `self.master.event_generate(<<IDLE>>, state = 0, when - 'tail')` will be put inside `class VKeyboard` if not in `__init__` it will be put in `def on_event(self, event)` since it's where the `touch/click` gets processed...?

**Comment by WK-GiHu** [comment]
@Justinjay282 

>it will be put in def on_event(self, event) since it's where the touch/click gets processed...?

Yes, do so
