### ISSUE TITLE
VKeyboard.py

### ISSUE THREAD

**Issue by WK-GiHu** [Justinjay282/qwerty#4]
@Justinjay282 

1. Make `VKeyboard.py` a Python `module` so you can `import` it into `App.py`.
  Add at the bottom, for testing this module add the shown three lines of code
  ```
  if __name__ ....
    root = tk.Tk()
    main = VKeyboard(root)
    root.mainloop()
  ```
2. Wrap your code into a `class VKeyboard(tk.Toplevel):`
  ```
class VKeyboard(tk.Toplevel):
    INSTANCE = None

    def __init__(self, parent):
       # here goes the settings for the Toplevel

   def create(self):
       # as is

   def select(self, value):
       # as is

    @classmethod
    def entry(cls, master, entry):
        if cls.INSTANCE is None:
            cls.INSTANCE = cls(master)
        else:
            cls.INSTANCE.deiconify()
            
        cls.INSTANCE.entry = entry
        
    @classmethod
    def withdraw(cls):
        if cls.INSTANCE is not None:
            tk.Toplevel.withdraw(cls.INSTANCE)
  ```

### Update after edit, so i can review

**Comment by Justinjay282** [comment]
Hi sir, I've edited the code. did I edit it right?

**Comment by WK-GiHu** [comment]
@Justinjay282 

Don't forget to set @WK-GiHu 

---

> edited the Vkeyboard.py.

**Review**

- [ ] Move this Line 7 into `def create(...`
https://github.com/Justinjay282/qwerty/blob/c907e137bbdd00d6e1dd5d0b67081a00841d95aa/VKeyboard.py#L7

- [ ] Move the following **three** Lines into `__init__`
https://github.com/Justinjay282/qwerty/blob/c907e137bbdd00d6e1dd5d0b67081a00841d95aa/VKeyboard.py#L42

  - [ ] Replace the **first** line with
    ```
    super().__init__(parent)
    ```

- [ ] Add the following to `__init__`
    ```
        self.create()
        self.uppercase = False
        self.entry = None
    ```
- [ ] Change to the same definition as in my comment: https://github.com/Justinjay282/qwerty/issues/4#issue-562661843
  The first arguement in a **Class method** have allways to be `self`.
https://github.com/Justinjay282/qwerty/blob/c907e137bbdd00d6e1dd5d0b67081a00841d95aa/VKeyboard.py#L17
  https://github.com/Justinjay282/qwerty/blob/c907e137bbdd00d6e1dd5d0b67081a00841d95aa/VKeyboard.py#L40

**Comment by Justinjay282** [comment]
@WK-GiHu, I've edited the code. I'm confused about replacing the first line with `super.__init__(parent) and Move the following Lines to `__init__`. I changed the `def select(entry,value)` to def `select(self,entry,value)` and also `def create` also changed the `self.select` and `self.create`

**Comment by WK-GiHu** [comment]
@Justinjay282 

>I'm confused about replacing the first line

It's `OOP` syntax, the definiton `class <name of your class>(tk.Toplevel)` will instantiate `tk.Toplevel` if called. Therefore `super().__init__(...` is the same as `window = tk.Toplevel(...`

- [ ] Remove Line 7
https://github.com/Justinjay282/qwerty/blob/798de972c2ed70daffd51a42cb43ee7431d30f39/VKeyboard.py#L7

- [ ] Rename Line 8 and 9 from `windows....` to `self....`.
  This object `VKeyboard` **is** a `Toplevel`, therefore all `Toplevel` related `method/attribute` are accessed using prefx `self.`

### to be continued ....

**Comment by Justinjay282** [comment]
@WK-GiHu thank you for your explanation. I got it now :) I'm done editing the code.

**Comment by WK-GiHu** [comment]
@Justinjay282 

### Review `def select(...`

- [ ] Please fulfill as requested and click the checkmark.
  - [ ] Change to the same definition as in my comment: https://github.com/Justinjay282/qwerty/issues/4#issue-562661843

- [ ] Remove Line 15 and **prefix** all `uppercase` with `self.upercase`
https://github.com/Justinjay282/qwerty/blob/798de972c2ed70daffd51a42cb43ee7431d30f39/VKeyboard.py#L15

- [ ] **Prefix** all `entry` with `self.entry`

### to be continued

**Comment by Justinjay282** [comment]
@WK-GiHu, I've edited the code. I didn't change the `entry` to `self.entry` in `@classmethod`

**Comment by WK-GiHu** [comment]
@Justinjay282 

### Review `def create(...`

- [ ] Please fulfill as requested and click the checkmark.
  - [ ] Change to the same definition as in my comment: https://github.com/Justinjay282/qwerty/issues/4#issue-562661843

- [ ] Change to
https://github.com/Justinjay282/qwerty/blob/798de972c2ed70daffd51a42cb43ee7431d30f39/VKeyboard.py#L64
    ```
    .Button(self,
    ```
- [ ] Change to
https://github.com/Justinjay282/qwerty/blob/798de972c2ed70daffd51a42cb43ee7431d30f39/VKeyboard.py#L65
    ```
    .select(value)
    ```

**Comment by WK-GiHu** [comment]
@Justinjay282 

> I didn't change the entry to self.entry in @classmethod

OK, thats a parameter not a `class attribute`

**Comment by Justinjay282** [comment]
@WK-GiHu, sir, I changed the `self.entry(entry, value)` to `self.entry(value)` change the `tk.Button(window...)` to `tk.Button(self,...)` I'm done editing now.

**Comment by WK-GiHu** [comment]
@Justinjay282 

One mistake of mine, this should read `def __init__(self, parent):`

- [ ] You have still not fulfilled!
  - [ ] Change to the same definition as in my comment: https://github.com/Justinjay282/qwerty/issues/4#issue-562661843

OK, after the above is done let the Python interpreter show us the errors.
Run `python VKeyboard.py` and show the errors.

**Comment by Justinjay282** [comment]
`Traceback (most recent call last):
  File "D:/SchoolApp/Python/ew.py", line 83, in <module>
    main = VKeyboard(root)
  File "D:/SchoolApp/Python/ew.py", line 9, in __init__
    self.create()
TypeError: create() missing 2 required positional arguments: 'root' and 'entry'`
it is because we don't have an entry yet right?

**Comment by WK-GiHu** [comment]
@Justinjay282 

Please, insert the Traceback as `Code` using either the Symbol `<>` or enclosing it within three Backticks. 

---

>`TypeError: create() missing 2 required positional arguments: 'root' and 'entry'`

- [ ] You have still not fulfilled!
  - [ ] Change to the same definition as in my comment: https://github.com/Justinjay282/qwerty/issues/4#issue-562661843

### Compare with my comment, edit and run again

**Comment by Justinjay282** [comment]
@WK-GiHu I will insert it in my VKeyboard.py? using three backticks right?

**Comment by Justinjay282** [comment]
@WK-GiHu, sir, I just changed my comment and enclosed it with three backticks.

**Comment by WK-GiHu** [comment]
@Justinjay282 

>because we don't have an entry yet right?

- [ ] Extend the `__main__` 
https://github.com/Justinjay282/qwerty/blob/c3155ad61ccd87f4f4915d22627383cf31b3fee9/VKeyboard.py#L81
with
    ```
    root = tk.Tk()
    entry = tk.Entry(root)
    entry.grid()
    VKeyboard.entry(root, entry)
    root.mainloop()
    ```

**Comment by Justinjay282** [comment]
@WK-GiHu,sir, still getting the same error. I've edited the code

**Comment by WK-GiHu** [comment]
@Justinjay282 

>@WK-GiHu,sir, still getting the same error. I've edited the code

You will see this error as long as you don't fulfill https://github.com/Justinjay282/qwerty/issues/4#issuecomment-584237626

**Comment by Justinjay282** [comment]
@WK-GiHu, I will change the `def select(self, entry, value):` and `def create(self, root, entry):` to?

**Comment by WK-GiHu** [comment]
@Justinjay282 

### Yes, same as in my first comment

**Comment by Justinjay282** [comment]
@WK-GiHu, Oh my, I'm so sorry, I didn't notice that. I'm done editing the code. There's no error when I run, the virtual keyboard is popping along with the entry in root.

**Comment by WK-GiHu** [comment]
@Justinjay282 

>

There is indentation error, dedent the Line  75 and add a NewLine before and after it
https://github.com/Justinjay282/qwerty/blob/a1800f6317918cdc4d64f2682fa05acd1b716d55/VKeyboard.py#L75

**Comment by Justinjay282** [comment]
@WK-GiHu, I've edited the code. It's working now. I can finally type on the entry.

**Comment by WK-GiHu** [comment]
@Justinjay282 

>It's working now

OK, I'm offline now for 2 hours.
I will come back to continue with `App.py`

**Comment by Justinjay282** [comment]
@WK-GiHu, thank you so much, sir. I'll also go to sleep now since it's 2 am in my country. I'll immediately go here when I woke up. Thank you so much again, sir. I don't know how I can repay you. I am happy since this is my last piece to complete my thesis. Thank you so much.

**Comment by WK-GiHu** [comment]
@Justinjay282 

Accept my answer on Stackoverflow

- [Stackoverflow - how-to-call-and-close-a-virtual-keyboard-made-by-tkinter-using-touchscreen-displ](https://stackoverflow.com/questions/60136473)
